#!/usr/bin/env python3
"""
GenAI assistant for the GitHub Actions CI/CD pipeline.

Supports company-provided Ollama servers and the Google Gemini Developer API.
Only the Python standard library is used, so nothing needs to be installed.

Commands:
    check              Test connectivity to the configured AI provider
  summarize-logs     Summarize CI/CD log files into a build / deployment report
  release-notes      Create release notes / changelog from git history
  generate-docs      Generate documentation for the ETL pipeline code
  review-workflows   Review GitHub workflow YAML files (validation + optimization tips)
  generate-workflow  Draft a NEW workflow YAML from a plain-English description

Configuration (environment variables):
    AI_PROVIDER      Provider: ollama (default) or gemini
  OLLAMA_URLS      Comma-separated server URLs, tried in order (automatic failover)
  OLLAMA_MODEL     Preferred model, e.g. llama3 (falls back to the first installed model)
  OLLAMA_USERNAME  Optional - only needed if the servers are behind a basic-auth proxy
  OLLAMA_PASSWORD  Optional - only needed if the servers are behind a basic-auth proxy
    GEMINI_API_KEY   API key for the Gemini Developer API
    GEMINI_MODEL     Gemini model (default gemini-3.7-flash; other models are tried automatically)
    AI_TIMEOUT       Generation timeout in seconds (default 300)

Examples:
  python scripts/ai_assistant.py check
  python scripts/ai_assistant.py summarize-logs --input-dir logs --output ai_reports/log_summary.md
  python scripts/ai_assistant.py generate-workflow --description "Run pytest on every PR"
"""
import argparse
import base64
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_URLS = "http://172.18.0.2:11434,http://172.18.0.3:11434,http://172.18.0.4:11434"
DEFAULT_MODEL = "llama3"
DEFAULT_GEMINI_MODEL = "gemini-3.7-flash"
GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models"
# Tried in order when the preferred model is overloaded, rate-limited or not available for this key.
GEMINI_FALLBACK_MODELS = (
    "gemini-3.7-flash",
    "gemini-3.5-flash-lite",
    "gemini-3.8-flash",
)
GEMINI_ATTEMPTS = 3
GEMINI_MAX_RETRY_WAIT = 60
RETRYABLE_HTTP_CODES = (429, 500, 502, 503, 504)
# Model-specific errors (shut down / no access / not found) -> skip to the next model.
SKIP_MODEL_HTTP_CODES = (400, 403, 404)
PROVIDERS = ("ollama", "gemini")
MAX_CONTEXT_CHARS = 12000
AI_DISCLAIMER = "> **Note:** Generated by AI. Review for accuracy before publishing."
SYSTEM_PROMPT = (
    "You are a senior DevOps and Databricks engineer. "
    "Answer in clear, concise Markdown. Only state facts that are present in the provided input."
)

# The Ollama servers are on the internal network, so bypass any corporate HTTP proxy.
_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))


class AIUnavailableError(RuntimeError):
    """Raised when the configured AI provider could not produce an answer."""


# -----------------------------------------------------------------------------
# Ollama helpers
# -----------------------------------------------------------------------------
def get_server_urls():
    """Read and validate server URLs (only http/https are allowed)."""
    urls = []
    for item in (os.getenv("OLLAMA_URLS") or DEFAULT_URLS).split(","):
        url = item.strip().rstrip("/")
        if not url:
            continue
        if urllib.parse.urlparse(url).scheme not in ("http", "https"):
            raise ValueError(f"Invalid Ollama URL (must start with http:// or https://): {url}")
        urls.append(url)
    return urls


def _headers():
    headers = {"Content-Type": "application/json"}
    username, password = os.getenv("OLLAMA_USERNAME"), os.getenv("OLLAMA_PASSWORD")
    if username and password:
        token = base64.b64encode(f"{username}:{password}".encode("utf-8")).decode("ascii")
        headers["Authorization"] = f"Basic {token}"
    return headers


def _call_api(url, payload=None, timeout=15):
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    # URL scheme is validated in get_server_urls(), so bandit B310 is a false positive here.
    request = urllib.request.Request(  # nosec B310
        url, data=data, headers=_headers(), method="POST" if data else "GET"
    )
    with _OPENER.open(request, timeout=timeout) as response:
        return json.loads(response.read().decode("utf-8"))


def list_models(base_url):
    data = _call_api(f"{base_url}/api/tags")
    return [model.get("name", "") for model in data.get("models", []) if model.get("name")]


def choose_model(available, preferred):
    """Use the preferred model if installed (with or without ':tag'), else the first one."""
    if preferred in available:
        return preferred
    for name in available:
        if name.split(":")[0] == preferred.split(":")[0]:
            return name
    return available[0] if available else None


def ask_ai(prompt):
    """Send a prompt to the selected AI provider."""
    provider = os.getenv("AI_PROVIDER", "ollama").strip().lower()
    timeout = int(os.getenv("AI_TIMEOUT") or os.getenv("OLLAMA_TIMEOUT") or "300")
    if provider == "gemini":
        return ask_gemini(prompt, timeout)
    if provider != "ollama":
        raise AIUnavailableError(f"Unsupported AI_PROVIDER '{provider}' (use one of: {', '.join(PROVIDERS)})")

    preferred = os.getenv("OLLAMA_MODEL") or DEFAULT_MODEL
    errors = []

    for base_url in get_server_urls():
        try:
            model = choose_model(list_models(base_url), preferred)
            if not model:
                errors.append(f"{base_url}: no models installed")
                continue
            print(f"Asking model '{model}' on {base_url} ...")
            payload = {
                "model": model,
                "system": SYSTEM_PROMPT,
                "prompt": prompt,
                "stream": False,
                "options": {"temperature": 0.2},
            }
            answer = _call_api(f"{base_url}/api/generate", payload, timeout=timeout).get("response", "").strip()
            if answer:
                return answer
            errors.append(f"{base_url}: empty response")
        except (OSError, ValueError) as error:  # URLError, timeouts and bad JSON are covered here
            errors.append(f"{base_url}: {error}")

    raise AIUnavailableError(" | ".join(errors) or "no Ollama servers configured")


def _gemini_call(model, payload=None, timeout=15):
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise AIUnavailableError("GEMINI_API_KEY is required when AI_PROVIDER=gemini")
    url = f"{GEMINI_API_BASE}/{urllib.parse.quote(model, safe='')}"
    if payload is not None:
        url += ":generateContent"
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json", "x-goog-api-key": api_key},
        method="POST" if data else "GET",
    )
    # Default opener honors HTTPS proxies; URL is built from a fixed https constant (bandit B310 false positive).
    with urllib.request.urlopen(request, timeout=timeout) as response:  # nosec B310
        return json.loads(response.read().decode("utf-8"))


def _gemini_error_details(error, attempt):
    """Return (seconds to wait, readable message) from a Gemini HTTP error."""
    delay, message = 10 * attempt, error.reason
    retry_after = error.headers.get("Retry-After") if error.headers else None
    if retry_after and retry_after.isdigit():
        delay = int(retry_after)
    try:
        body = json.loads(error.read().decode("utf-8")).get("error", {})
        message = body.get("message") or message
        for detail in body.get("details", []):
            if str(detail.get("@type", "")).endswith("RetryInfo"):
                delay = float(str(detail.get("retryDelay", "0")).rstrip("s") or 0)
    except (OSError, ValueError, AttributeError, TypeError):
        pass
    return min(max(delay, 1), GEMINI_MAX_RETRY_WAIT), str(message)[:200]


def ask_gemini(prompt, timeout):
    """Generate a response using Google's Gemini Developer API (with retries and model fallback)."""
    preferred = os.getenv("GEMINI_MODEL") or DEFAULT_GEMINI_MODEL
    models = [preferred] + [m for m in GEMINI_FALLBACK_MODELS if m != preferred]
    payload = {
        "systemInstruction": {"parts": [{"text": SYSTEM_PROMPT}]},
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.2},
    }
    errors = []
    # Cap each request so an overloaded model cannot block the whole run.
    timeout = min(timeout, int(os.getenv("GEMINI_TIMEOUT") or "90"))
    for model in models:
        for attempt in range(1, GEMINI_ATTEMPTS + 1):
            print(f"Asking model '{model}' on Gemini (attempt {attempt}/{GEMINI_ATTEMPTS}) ...")
            try:
                response = _gemini_call(model, payload, timeout=timeout)
            except urllib.error.HTTPError as error:
                wait, message = _gemini_error_details(error, attempt)
                errors.append(f"{model}: HTTP {error.code} {message}")
                if error.code in RETRYABLE_HTTP_CODES:
                    if attempt < GEMINI_ATTEMPTS:
                        print(f"HTTP {error.code} from '{model}', waiting {wait:.0f}s before retrying ...")
                        time.sleep(wait)
                    continue
                if error.code in SKIP_MODEL_HTTP_CODES:
                    break
                raise AIUnavailableError(" | ".join(errors)) from error
            except (TimeoutError, urllib.error.URLError) as error:
                errors.append(f"{model}: {error}")
                break  # slow or unreachable model -> try the next model
            except (OSError, ValueError) as error:
                raise AIUnavailableError(f"Gemini API request failed: {error}") from error

            candidates = response.get("candidates", [])
            if candidates:
                parts = candidates[0].get("content", {}).get("parts", [])
                answer = "\n".join(part.get("text", "") for part in parts).strip()
                if answer:
                    return answer
            raise AIUnavailableError("Gemini API returned no text (the prompt may have been blocked)")
        print(f"Model '{model}' is unavailable, trying the next one ...")
    raise AIUnavailableError("All Gemini models failed: " + " | ".join(errors))


# -----------------------------------------------------------------------------
# Input / output helpers
# -----------------------------------------------------------------------------
def redact_secrets(text):
    """Never send secrets to the AI: mask known secret values and Databricks tokens."""
    for var in ("DATABRICKS_TOKEN", "DATABRICKS_HOST", "OLLAMA_PASSWORD", "GEMINI_API_KEY"):
        value = os.getenv(var)
        if value:
            text = text.replace(value, f"<{var}>")
    return re.sub(r"dapi[0-9a-f]{16,}(-\d+)?", "<REDACTED_TOKEN>", text)


def read_files(paths, keep_tail=False):
    """Read files into one text block, trimmed to fit the model context.

    keep_tail=True keeps the END of each file (errors in logs are usually at the end).
    """
    if not paths:
        return "(no files found)"
    per_file = max(1000, MAX_CONTEXT_CHARS // len(paths))
    parts = []
    for path in paths:
        text = path.read_text(encoding="utf-8", errors="replace")
        if len(text) > per_file:
            text = ("...(trimmed)...\n" + text[-per_file:]) if keep_tail else (text[:per_file] + "\n...(trimmed)...")
        parts.append(f"===== FILE: {path.as_posix()} =====\n{text}")
    return redact_secrets("\n\n".join(parts))


def run_git(*args):
    try:
        # Fixed git command without a shell -> safe (bandit B603/B607).
        result = subprocess.run(  # nosec B603 B607
            ["git", *args], capture_output=True, text=True, encoding="utf-8", errors="replace", check=False
        )
    except FileNotFoundError:
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def write_report(output, title, body, used_ai):
    """Write a Markdown report and also show it on the GitHub Actions run summary page."""
    path = Path(output)
    path.parent.mkdir(parents=True, exist_ok=True)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    commit = (os.getenv("GITHUB_SHA") or "local")[:7]

    lines = [f"# {title}", "", f"_Generated: {generated} | Commit: {commit}_", ""]
    if used_ai:
        lines += [AI_DISCLAIMER, ""]
    lines += [body.strip(), ""]
    content = "\n".join(lines)

    path.write_text(content, encoding="utf-8")
    summary_file = os.getenv("GITHUB_STEP_SUMMARY")
    if summary_file:
        with open(summary_file, "a", encoding="utf-8") as handle:
            handle.write(content + "\n")
    print(f"Report written to {path}")


def create_report(title, prompt, fallback, output):
    """Ask the AI; if every server is down, write a non-AI fallback report instead of failing."""
    try:
        body, used_ai = ask_ai(prompt), True
    except AIUnavailableError as error:
        print(f"::warning::GenAI unavailable - writing fallback report. Details: {error}")
        body, used_ai = "**AI was unavailable.** Raw information:\n\n" + fallback, False
    write_report(output, title, body, used_ai)
    return 0


def list_files(folder, patterns):
    root = Path(folder)
    found = set()
    for pattern in patterns:
        found.update(p for p in root.glob(pattern) if p.is_file())
    return sorted(found)


# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
def cmd_check(_args):
    provider = os.getenv("AI_PROVIDER", "ollama").strip().lower()
    if provider == "gemini":
        model = os.getenv("GEMINI_MODEL") or DEFAULT_GEMINI_MODEL
        try:
            _gemini_call(model)
            print(f"[OK]   Gemini API -> model: {model}")
            return 0
        except (AIUnavailableError, OSError, ValueError) as error:
            print(f"[FAIL] Gemini API -> {error}")
            return 1
    if provider != "ollama":
        print(f"[FAIL] Unsupported AI_PROVIDER '{provider}' (use one of: {', '.join(PROVIDERS)})")
        return 1

    reachable = False
    for url in get_server_urls():
        try:
            models = list_models(url)
            print(f"[OK]   {url} -> models: {', '.join(models) or '(none installed)'}")
            reachable = reachable or bool(models)
        except (OSError, ValueError) as error:
            print(f"[FAIL] {url} -> {error}")
    return 0 if reachable else 1


def cmd_summarize_logs(args):
    files = list_files(args.input_dir, ["**/*.log", "**/*.xml", "**/*.txt"])
    prompt = (
        "Summarize these GitHub Actions CI/CD logs. The pipeline lints and tests code, then deploys a "
        "Databricks ETL job (bronze/silver/gold) to QA (qa_catalog) and PROD (prod_catalog).\n"
        "Use exactly these Markdown sections:\n"
        "## Overall Status\n"
        "## Stages (a table: Stage | Result | Notes)\n"
        "## Errors and Warnings\n"
        "## Probable Root Cause\n"
        "## Recommended Fixes\n"
        "If everything passed, say so clearly and keep the error sections short.\n\n"
        f"LOGS:\n{read_files(files, keep_tail=True)}"
    )
    fallback = "Log files analysed:\n" + "\n".join(f"- {f.as_posix()}" for f in files)
    if not files:
        fallback = "No log files found."
    return create_report(args.title, prompt, fallback, args.output)


def cmd_release_notes(args):
    commits = run_git("log", f"-n{args.max_commits}", "--date=short", "--pretty=format:%h | %ad | %an | %s")
    changed = run_git("log", f"-n{args.max_commits}", "--stat", "--pretty=format:--- %h %s")
    prompt = (
        "Write release notes for this Databricks ETL CI/CD project from the git history below.\n"
        "Use these Markdown sections: ## Highlights, ## New Features, ## Fixes, "
        "## Pipeline / DevOps Changes, ## Changelog (one bullet per commit with its short hash).\n"
        "Skip empty sections.\n\n"
        f"COMMITS:\n{redact_secrets(commits)}\n\nCHANGED FILES:\n{redact_secrets(changed)[:MAX_CONTEXT_CHARS]}"
    )
    fallback = "```\n" + (commits or "No git history available.") + "\n```"
    return create_report("Release Notes", prompt, fallback, args.output)


def cmd_generate_docs(args):
    files = list_files(".", ["src/*.py", "resources/*.yml", "databricks.yml"])
    prompt = (
        "Generate technical documentation for this Databricks ETL project.\n"
        "Use these Markdown sections: ## Purpose, ## Architecture (bronze -> silver -> gold), "
        "## Tables Created (table: Layer | Table | Description), ## Environments (QA and PROD use separate "
        "Unity Catalog catalogs in one Databricks Free Edition workspace), ## Job Tasks, ## How to Run.\n\n"
        f"SOURCE FILES:\n{read_files(files)}"
    )
    fallback = "Files:\n" + "\n".join(f"- {f.as_posix()}" for f in files)
    return create_report("Pipeline Documentation", prompt, fallback, args.output)


def cmd_review_workflows(args):
    files = list_files(".", [".github/workflows/*.yml", ".github/workflows/*.yaml"])
    prompt = (
        "Review these GitHub Actions workflow files.\n"
        "Check: syntax/logic errors, secret handling, permissions (least privilege), action version "
        "pinning, reliability (timeouts, concurrency), performance (caching) and reusability.\n"
        "Return a Markdown table: Severity (High/Medium/Low) | File | Finding | Suggestion, "
        "followed by a short ## Overall Assessment.\n\n"
        f"WORKFLOWS:\n{read_files(files)}"
    )
    fallback = "Workflow files:\n" + "\n".join(f"- {f.as_posix()}" for f in files)
    return create_report("Workflow Review", prompt, fallback, args.output)


def cmd_generate_workflow(args):
    prompt = (
        "Create a GitHub Actions workflow YAML for this requirement:\n"
        f"{args.description}\n\n"
        "Rules: use only official actions (actions/*, databricks/setup-cli), set 'permissions: contents: read', "
        "read credentials only from ${{ secrets.* }}, add timeout-minutes, add short comments. "
        "Return ONLY the YAML inside one ```yaml code block."
    )
    try:
        answer = ask_ai(prompt)
    except AIUnavailableError as error:
        print(f"GenAI unavailable: {error}")
        return 1

    match = re.search(r"```(?:ya?ml)?\s*\n(.*?)```", answer, re.DOTALL)
    yaml_text = (match.group(1) if match else answer).strip()
    header = (
        "# AI-GENERATED DRAFT - review and test manually before committing.\n"
        f"# Requirement: {' '.join(args.description.split())}\n"
    )
    path = Path(args.output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + yaml_text + "\n", encoding="utf-8")
    print(f"Draft workflow written to {path}")
    return 0


def build_parser():
    parser = argparse.ArgumentParser(description="GenAI assistant for CI/CD (Ollama or Gemini)")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("check", help="Test configured AI provider connectivity").set_defaults(func=cmd_check)

    p = sub.add_parser("summarize-logs", help="Summarize CI/CD logs")
    p.add_argument("--input-dir", default="logs")
    p.add_argument("--title", default="CI/CD Log Summary")
    p.add_argument("--output", default="ai_reports/log_summary.md")
    p.set_defaults(func=cmd_summarize_logs)

    p = sub.add_parser("release-notes", help="Create release notes from git history")
    p.add_argument("--max-commits", type=int, default=20)
    p.add_argument("--output", default="ai_reports/release_notes.md")
    p.set_defaults(func=cmd_release_notes)

    p = sub.add_parser("generate-docs", help="Generate pipeline documentation")
    p.add_argument("--output", default="ai_reports/pipeline_documentation.md")
    p.set_defaults(func=cmd_generate_docs)

    p = sub.add_parser("review-workflows", help="Review workflow YAML files")
    p.add_argument("--output", default="ai_reports/workflow_review.md")
    p.set_defaults(func=cmd_review_workflows)

    p = sub.add_parser("generate-workflow", help="Draft a workflow from a description")
    p.add_argument("--description", required=True)
    p.add_argument("--output", default="ai_reports/generated_workflow.yml")
    p.set_defaults(func=cmd_generate_workflow)

    return parser


def main():
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
